version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: swipeforjobs-postgres
    environment:
      POSTGRES_DB: swipeforjobs_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: swipeforjobs-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: